CC=zcc
AR=z88dk-z80asm

########### BUILD CONFIGURATION ##############

# Enables a faster version of SMS_addSprite (and SMS_add*AdjoiningSprites)
# which does not return a handle and does not check for sprite terminator
# and sprite availability
#CONFIG+=-DNO_SPRITE_CHECKS

# Enables a faster version of SMS_add*AdjoiningSprites through disabling
# support for zoomed sprites
#CONFIG+=-DNO_SPRITE_ZOOM

# Enable support for Megadrive controllers
#CONFIG+=-DMD_PAD_SUPPORT

# Enable support for VDP type detection
#CONFIG+=-DVDPTYPE_DETECTION

# Build a lib supporting less sprites to save memory. Max is 64 (all).
#CONFIG+=-DMAXSPRITES=64

# Omit support for a frame interrupt hook to save a few bytes
# and cycles.
#CONFIG+=-DNO_FRAME_INT_HOOK

############# END OF BUILD CONFIG OPTIONS #############

OPT=--max-allocs-per-node100000 -SO3 -O3
CFLAGS=+sms -compiler=sdcc $(OPT) $(CONFIG)
PEEP_OPTIONS=-custom-copt-rules=rules.copt

OUTPUT_LIBS=SMSlib.lib SMSlib_GG.lib

# Files that are compiled once and used for SMS and GG
SRCS=SMSlib_aPLib.c SMSlib_autotext.c SMSlib_deprecated.c SMSlib_load1bppTiles.c SMSlib_load2bppTiles.c SMSlib_loadTileMapArea.c SMSlib_loadTileMapColumn.c SMSlib_paddle.c SMSlib_paletteAdd.c SMSlib_paletteSub.c SMSlib_STC0comp.c SMSlib_STC4comp.c SMSlib_PSGaiden.c  SMSlib_spriteAdv.c SMSlib_sprite.c SMSlib_STMcomp.c SMSlib_textrenderer.c SMSlib_twosprites.c SMSlib_threesprites.c SMSlib_foursprites.c SMSlib_metasprite.c SMSlib_UNSAFE.c SMSlib_UNSAFE_SAT.c SMSlib_UNSAFE_memcpy.c SMSlib_UNSAFE_aPLib.c SMSlib_VRAMmemcpy_brief.c SMSlib_VRAMmemcpy.c SMSlib_VRAMmemset.c SMSlib_zx7.c SMSlib_zx7_VRAM.c SMSlib_string.c SMSlib_getTile.c SMSlib_readVRAM.c SMSlib_debug.c

# One .c.o per common source file. Add target specific .c.o dependencies here.
OBJS_SMS=$(patsubst %.c,%.c.o,$(SRCS)) SMSlib.c.o SMSlib_autotext.c.o SMSlib_spriteClip.c.o SMSlib_paletteZero.c.o SMSlib_paletteAdv.c.o
OBJS_GG=$(patsubst %.c,%.c.o,$(SRCS)) SMSlib_GG.c.o SMSlib_autotext_GG.c.o SMSlib_spriteClip_GG.c.o SMSlib_paletteZero_GG.c.o SMSlib_paletteAdv_GG.c.o

ALL: $(OUTPUT_LIBS)

# Library outputs
SMSlib.lib: $(OBJS_SMS)
	$(AR) -x$@ $^

SMSlib_GG.lib: $(OBJS_GG)
	$(AR) -x$@ $^


# Specific rules for some files with particular compilation options or specific
# to a target.

SMSlib.c.o: SMSlib.c SMSlib.h peep-rules.txt
	#$(CC) $(CFLAGS) $(PEEP_OPTIONS) --reserve-regs-iy -c -o $@ $<
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $<

SMSlib_GG.c.o: SMSlib.c SMSlib.h peep-rules.txt
	#$(CC) $(CFLAGS) $(PEEP_OPTIONS) --reserve-regs-iy -c -o $@ $< -DTARGET_GG
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $< -DTARGET_GG

SMSlib_autotext_GG.c.o: SMSlib_autotext.c SMSlib.h peep-rules.txt
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $< -DTARGET_GG

SMSlib_spriteClip_GG.c.o: SMSlib_spriteClip.c SMSlib.h peep-rules.txt
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $< -DTARGET_GG

SMSlib_paletteZero_GG.c.o: SMSlib_paletteZero.c SMSlib.h peep-rules.txt
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $< -DTARGET_GG

SMSlib_paletteAdv_GG.c.o: SMSlib_paletteAdv.c SMSlib.h peep-rules.txt
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $< -DTARGET_GG

# The following are compiled without --peep-rules
SMSlib_zx7.c.o: SMSlib_zx7.c
	$(CC) $(CFLAGS) -c -o $@ $<

SMSlib_UNSAFE_zx7.c.o: SMSlib_UNSAFE_zx7.c
	$(CC) $(CFLAGS) -c -o $@ $<

SMSlib_aPLib.c.o: SMSlib_aPLib.c
	$(CC) $(CFLAGS) -c -o $@ $<

SMSlib_paddle.c.o: SMSlib_paddle.c
	$(CC) $(CFLAGS) -c -o $@ $<

# Default rules
%.c.o: %.c SMSlib.h peep-rules.txt
	$(CC) $(CFLAGS) $(PEEP_OPTIONS) -c -o $@ $<

clean:
	rm -f $(OUTPUT_LIBS) $(OBJS_SMS) $(OBJS_GG) *.lst *.sym *.asm
